server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  application:
    name: craftory-ai

  datasource:
    url: jdbc:mysql://mysql:3306/CraftConnect
    username: ${DB_USERNAME:CraftConnect-MySQL}
    password: ${DB_PASSWORD:RishabhGupta&2005@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
          max-tokens: 1000
      image:
        options:
          model: dall-e-3

  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24 hours

logging:
  level:
    com.craftory: DEBUG
    org.springframework.ai: DEBUG
    org.hibernate.SQL: DEBUG

app:
  upload:
    dir: ${UPLOAD_DIR:./uploads}
  ai:
    retry-attempts: 3
    timeout: 30s
